freeCodeCamp/forum-theme

common/header.html

In freeCodeCamp.org/learn and freeCodeCamp.org/news it states in the search bar that it is 6,000 activities +. However, on the forum, it states 5,000+ activities.
Closes: [#38794](https://github.com/freeCodeCamp/freeCodeCamp/issues/38794) on the [main repository](https://github.com/freeCodeCamp/freeCodeCamp)

fixed activities count for consistency

---

README.md
common/header.html

Stuff we removed in https://github.com/freeCodeCamp/forum-theme/commit/3ebb1c6846718718d28d100db03957638144a143

fix: navigation header getURL calls

---

about.json
common/common.scss

closes freecodecamp/freecodecamp#39503 
closes freecodecamp/freecodecamp#38417
closes freecodecamp/freecodecamp#38244
closes freecodecamp/freecodecamp#39366
closes freecodecamp/freecodecamp#38244

fix: remove words in favor of icons

---

common/head_tag.html

Checklist:
Closes #XXXXX
Link and Title values were accidentally swapped.

fix: footer links

---

common/common.scss

Checklist:
Closes #XXXXX
Fix the z-index on the nav to prevent it overlapping the modal.

fix: z-index

---

common/common.scss

Checklist:
Closes #41830
In this issue [#41830](https://github.com/freeCodeCamp/freeCodeCamp/issues/41830) I said that there is a problem with hovering but the same issue applies for focusing the buttons so I also included that in the PR.

Fix inconsistent styling of icon buttons in the composer

---

README.md

Add discourse theme creator guide to docs

---

common/embedded.scss

Checklist:
Closes #XXXXX
Uses explicit hex colors rather than variables to fix errors.

fix: embedded styles colors

---

settings.yml

feat footer update March 2022

---

.github/workflows/yaml-lint.yml

Checklist:
Closes #XXXXX
Adds a simple action to lint the settings.yml file.

feat(tools): lint yaml in action

---

.github/workflows/yaml-lint.yml
.yamllint.yml

Checklist:
Closes #XXXXX
This should disable the `line-length` rule, as well as the rule that expects `---` at the top of the file.

feat: add yamllint config

---

common/common.scss

Checklist:
closes freeCodeCamp/freeCodeCamp/issues/47257

fix:freeCodeCamp/freeCodeCamp#47257

---

common/common.scss

Display the Updated topic banner in the DOM flow
Checklist:
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/48920

feat: position updated topic banner relatively

---

common/common.scss

fix: adjust hover and selected states

---

settings.yml

Checklist:
ref: https://github.com/freeCodeCamp/freeCodeCamp/issues/52259

fix: remove groups from footer

---

README.md

Checklist:
Replaces Gitter with Discord.

docs: update chat room link

---

common/common.scss

fix: curriculum button position

---

common/common.scss

fix: bring loader forward

---

common/common.scss

Checklist:
Closes #109
| Before | After |
| --- | --- |
| <img width="329" alt="Screenshot 2024-03-01 at 23 52 19" src="https://github.com/freeCodeCamp/forum-theme/assets/25715018/6cf1ad9b-e546-4947-a376-929a12a22d75"> | <img width="327" alt="Screenshot 2024-03-01 at 23 47 44" src="https://github.com/freeCodeCamp/forum-theme/assets/25715018/e6970b9c-a205-4b30-a833-a92fad2df26e"> |

fix: dropdown item color

---

common/head_tag.html

Add gpt script for consent management

---

common/head_tag.html

fix(ui): open articles in new tab

---

common/common.scss

fix: correct colour for nav icons

---

common/color_definitions.scss
common/common.scss

Checklist:
Closes #XXXXX
For some reason` --danger` isn't working but this should fix a few of my mistakes.

fix: color definition fixes

---

common/common.scss

Checklist:
Closes #125
It's taking too long for the pull request on the navbar component to be approved on Discourse so I'm adding this bit of CSS to fix the issue on our end.

fix: realign nav items
